#################
# customization #
#################

theme = "One Dark"

[font]
family = "FiraCode Nerd Font"
size = 14
weight = "normal"

###############
# single pane #
###############

# source: https://halloy.chat/guides/single-pane.html#single-pane

[actions.buffer]
click_channel_name = "replace-pane"
click_highlight = "replace-pane"
click_username = "replace-pane"
local = "replace-pane"
message_channel = "replace-pane"
message_user = "replace-pane"

[actions.sidebar]
buffer = "replace-pane"

###########
# servers #
###########

# [servers.liberachat]
# nickname = "rewgs"
# server = "irc.libera.chat"
# channels = ["#halloy"]

# open and free technology community
# [servers.oftc]
# nickname = "rewgs"
# server = "irc.oftc.net"       # "ircs://irc.oftc.net:6697"
# channels = ["#kernelnewbies"]

[servers.libera] # successor to freenode
nickname = "rewgs"
server = "irc.libera.chat"
channels = [
    "####music",
    "###hackers",
    "#alerts",
    "##AllNiteCafe",
    "##allpolitics",
    "##apple", # requires logged into NickServ account
    "#archlinux", # requires logged into NickServ account
    "#archlinux-offtopic", # requires logged into NickServ account
    "#debian", 
    "#kernel",
    "#linux", 
    "#linux-kernel", 
    "##mac-social",
    "##audio",
    "##backend",
    "#C++",
    "##C++",
    "##c++-basic",
    "##C++-meeting",
    "##C++-social",
    "#trading",
    "#stoicism",
    "#SolarPunk",
    "#socialism",
    "#social-dev",
    "#serenityos",
    "#rmstalk",
    "#robotics",
    "#machinelearning-general",
    "#ml-news",
    "#retrocomputing",
    "#indieweb",
    "#opensourcemusicians", # requires logged into NickServ account
    "#neovim",
    "#linuxmusicians",
    "#hackers",
    "#hackernews",
    "#go-nuts", #golang
    "#gnu",
    "#python",
    "#kernelnewbies",
    "##rust",
]

# FIXME:
# jupiter broadcasting
# [servers.jb]
# nickname = "rewgs"
# server = "irc.geekshed.net"
# channels = ["#jupiterbroadcasting"]

[servers.libera.sasl.plain]
username = "rewgs"
password_file = "/home/rewgs/sasl-pass"
password_file_first_line_only = true
