# Halloy config.
#
# For a complete list of available options,
# please visit https://halloy.chat/configuration/

[servers.liberachat]
nickname = "halloy6730"
server = "irc.libera.chat"
channels = ["#halloy"]
