# onedark
[colors.primary]
background = "#282c34"
foreground = "#abb2bf"
[colors.normal]
black = "#282c34"
white = "#abb2bf"
# light_red = "#e06c75"
# dark_red = "#be5046"
red = "#be5046" # dark
green = "#98c379"
# light_yellow = "#e5c07b"
# dark_yellow = "#d19a66"
yellow = "#d19a66" # dark
# blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
# gutter_grey = "#4b5263"
# comment_grey = "#5c6370"
